import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "./components/Sidebar/Sidebar";
import "./components/Sidebar/Sidebar.scss";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-zinc-50 font-sans dark:bg-black">
          <div className=" flex min-h-screen w-full ">
            <Sidebar />
            <main className="flex min-h-screen flex-1 flex-col items-center justify-between rounded-3xl bg-white px-8 pt-8 pb-[7px] dark:bg-black sm:items-start">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
